name: 🚀 Publish Package to npmjs

on:
  workflow_call:
  push:
    branches:
      - main

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  NPM_CONFIG_USERCONFIG: .npmrc

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: npm publish
